Lesson 10: Add web and API auth and profile
travka47/fefu_backend_2_3 pull request #12
Opened 2021-12-10 12:40 UTC by travka47

2021-12-10 14:55 UTC, chrn-feip requested changes

2021-12-10 14:55 UTC, chrn-feip commented on app/Http/Controllers/ApiAuthController.php
> +            'login' => 'unique:users|required|between:5, 30',
`Логин должен быть уникальным, от 5 до 30 символов, допускаются латинские буквы в любом регистре, цифры, дефис, знак подчёркивания. `

Где ограничения на алфавит?

2021-12-10 14:55 UTC, chrn-feip commented on app/Http/Controllers/RegistrationController.php
> +                    'login' => 'unique:users|required|between:5, 30',
Тоже ограничения на алфавит

2021-12-10 14:55 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +        @include('layouts.app')
Где этот файл в коммите?

2021-12-16 12:48 UTC, travka47 commented on resources/views/appeal.blade.php
> +        @include('layouts.app')
вроде, есть

2021-12-20 01:32 UTC, chrn-feip requested changes

2021-12-20 01:32 UTC, chrn-feip commented on app/Http/Controllers/ApiAuthController.php
> +            'login' => 'unique:users|required|between:5, 30|regex: /^[\w\-]+$/',
\w не делает ограничений на алфавит буквенных символов, а нам нужны только латинские, поэтому лучше взять a-z и добавить модификатор i. Цифры тоже надо будет добавить в таком случае. Не учтён знак подчёркивания.

2021-12-30 07:31 UTC, chrn-feip requested changes

2021-12-30 07:31 UTC, chrn-feip commented on app/Http/Controllers/ApiAuthController.php
> +            'login' => 'unique:users|required|between:5, 30|regex: /^[a-z\.-]+$/i',
> Цифры тоже надо будет добавить в таком случае. Не учтён знак подчёркивания.

2021-12-30 07:43 UTC, merged